version: '3.8'

services:
  tableorder-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/tableorder.db
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
    networks:
      - tableorder-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - tableorder-network

  # PostgreSQL service for production
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=tableorder
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tableorder-network

volumes:
  postgres_data:

networks:
  tableorder-network:
    driver: bridge
