apiVersion: apps/v1
kind: Deployment
metadata:
  name: tableorder-backend
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tableorder-backend
  template:
    metadata:
      labels:
        app: tableorder-backend
    spec:
      containers:
      - name: backend
        image: your-registry/tableorder-backend:latest
        ports:
        - containerPort: 5000
          name: http
        - containerPort: 5001
          name: https
        env:
        - name: ConnectionStrings__DefaultConnection
          value: "Host=postgres-service;Database=tableorder;Username=postgres;Password=$(POSTGRES_PASSWORD)"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tableorder-secrets
              key: POSTGRES_PASSWORD
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: tableorder-secrets
              key: JWT_SECRET_KEY
        - name: ADMIN_KEY
          valueFrom:
            secretKeyRef:
              name: tableorder-secrets
              key: ADMIN_KEY
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tableorder-secrets
              key: ADMIN_PASSWORD
        - name: STAFF_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tableorder-secrets
              key: STAFF_PASSWORD
        - name: JWT_ISSUER
          valueFrom:
            configMapKeyRef:
              name: tableorder-config
              key: JWT_ISSUER
        - name: JWT_AUDIENCE
          valueFrom:
            configMapKeyRef:
              name: tableorder-config
              key: JWT_AUDIENCE
        - name: JWT_EXPIRATION_MINUTES
          valueFrom:
            configMapKeyRef:
              name: tableorder-config
              key: JWT_EXPIRATION_MINUTES
        - name: ADMIN_USERNAME
          valueFrom:
            configMapKeyRef:
              name: tableorder-config
              key: ADMIN_USERNAME
        - name: STAFF_USERNAME
          valueFrom:
            configMapKeyRef:
              name: tableorder-config
              key: STAFF_USERNAME
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: tableorder-config
              key: ASPNETCORE_ENVIRONMENT
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: tableorder-backend-service
  namespace: default
spec:
  selector:
    app: tableorder-backend
  ports:
  - name: http
    port: 80
    targetPort: 5000
  - name: https
    port: 443
    targetPort: 5001
  type: ClusterIP
